### ISSUE TITLE
Chainsaw Software Distribution License

### ISSUE THREAD

**Issue by jlotthammer** [JudeWells/chainsaw#32]
Hi, Jude.

Cool work! I was taking a look at the chainsaw preprint and code and I didn't see a license for the project. Is this project fully open source? 

If so, I really recommend adding a permissive license for your project. [I can **_highly_** suggest the [MIT license](https://opensource.org/license/mit/)] or a similarly permissive license. See [here](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) for details on adding a license to the project. 

Please let me know.

Thanks in advance!

**Comment by JudeWells** [comment]
Thank you we have now added and MIT Licence.
