### ISSUE TITLE
Reproducibility: Datasets required

### ISSUE THREAD

**Issue by FoxHarley** [JudeWells/chainsaw#33]
Hello!

Great work on this project! 

In order to reproduce the performance evaluation, I would like to know which datasets were used for training and validating your approach. While the methodology in your paper is quite thorough, it does not offer a deterministic approach to generate these, and I can't find anything in your repo either.

Could you please either publish the identifiers of your data splits or provide some other means to reproduce the datasets?

Best regards,
Nicole

**Comment by FoxHarley** [comment]
Hey there! Any update?

**Comment by JudeWells** [comment]
The paper is currently under review for publication and we have been asked to benchmark against other models so will be submitting the training and validation datasets in the next couple of weeks.

**Comment by JudeWells** [comment]
The train / validation /  test splits are now uploaded in the`data_and_benchmarking` folder. The preprint has also been updated to show results on the new benchmarking dataset.

**Comment by KYQiu21** [comment]
Thanks very much for your efforts 👍
